// Copyright (c) 2026 TechLead 187 LLC
// SPDX-License-Identifier: BUSL-1.1

// desktop/renderer/trivia_bank.ts — P-TRIV.1 (ADR-0174): the SEED question bank.
//
// A static, first-party pack so the Trivia Wire works on first run and offline, and so a failed or
// malformed model generation (P-TRIV.2) always has something safe to fall back to — the game's own
// fail-closed floor. Every entry must pass isTriviaQuestion; the demo + tests enforce that, plus
// no-duplicate prompts and a spread of correct-answer positions (no "always C" tell).
//
// Keep prompts short (they scroll a 30px ticker) and explanations to ONE line — the explanation is
// where the learning happens, so it earns its scroll time.

import type { TriviaQuestion } from "./trivia.ts";

export const TRIVIA_BANK: readonly TriviaQuestion[] = [
  // ── python ──
  { topic: "python", q: "What does Python's walrus operator := do?", c: ["Compares identity", "Assigns a name inside an expression", "Unpacks a mapping", "Declares a constant"], a: 1, x: "PEP 572 assignment expressions bind a value as part of a larger expression, e.g. while (chunk := f.read(8192)):" },
  { topic: "python", q: "What is CPython's GIL?", c: ["A garbage-collector pause", "A bytecode cache", "A lock letting one thread run Python bytecode at a time", "An import sandbox"], a: 2, x: "The Global Interpreter Lock serializes bytecode execution per process - threads help I/O-bound work, not CPU-bound." },
  { topic: "python", q: "list.sort() vs sorted(xs): the key difference?", c: ["sort() is stable, sorted() is not", "sorted() mutates in place", "sort() mutates in place and returns None", "They are aliases"], a: 2, x: "xs.sort() reorders the list itself and returns None; sorted(xs) leaves it alone and returns a new list. Both are stable." },
  { topic: "python", q: "Why is def f(x=[]) a classic bug?", c: ["Lists cannot be defaults", "The default is evaluated once and shared across calls", "It shadows the built-in list", "It forces a copy per call"], a: 1, x: "Default values are evaluated at def time, so every call without x appends to the SAME list - use x=None and create inside." },
  { topic: "python", q: "What does yield inside a function make it?", c: ["A coroutine decorator", "A lazy import", "A thread target", "A generator function"], a: 3, x: "Calling it returns a generator; each yield hands out a value and pauses until the caller asks for the next one." },
  { topic: "python", q: "@dataclass mainly generates what for you?", c: ["__init__, __repr__ and __eq__ from the fields", "Runtime type checking", "JSON serialization", "Immutability by default"], a: 0, x: "dataclasses write the boilerplate methods from the annotated fields; frozen=True and asdict() are opt-ins, not defaults." },
  { topic: "python", q: "What does the with statement guarantee?", c: ["The block runs in a new thread", "__exit__ cleanup runs even if the block raises", "Variables stay local to the block", "The block is atomic"], a: 1, x: "A context manager's __exit__ always runs on the way out - that is why files, locks and transactions live in with blocks." },
  { topic: "python", q: "What does __slots__ on a class do?", c: ["Registers it as abstract", "Enables multiple inheritance", "Fixes the attribute set and drops the per-instance __dict__", "Makes attributes thread-safe"], a: 2, x: "__slots__ trades dynamic attributes for less memory per instance - handy when you create millions of small objects." },
  // ── typescript ──
  { topic: "typescript", q: "unknown differs from any because unknown...", c: ["is erased more aggressively", "allows every operation", "requires narrowing before use", "only exists under strict mode"], a: 2, x: "unknown is the type-safe any: you must narrow or assert before touching it, so mistakes surface at compile time." },
  { topic: "typescript", q: "What does readonly on a property actually enforce?", c: ["A frozen object at runtime", "Compile-time assignment checks only", "Deep immutability", "Serialization safety"], a: 1, x: "readonly is erased at compile time - the runtime object is still mutable; Object.freeze is the runtime tool." },
  { topic: "typescript", q: "A discriminated union narrows via what?", c: ["A shared literal tag property", "The in operator only", "Class inheritance", "Declaration order"], a: 0, x: "A common literal field like kind: \"circle\" | \"square\" lets a switch narrow each branch to its exact member." },
  { topic: "typescript", q: "keyof T evaluates to...", c: ["An array of property names", "A union of T's property-name literal types", "T's prototype chain", "The string type"], a: 1, x: "keyof {a: 1; b: 2} is the type \"a\" | \"b\" - the compile-time key union that powers safe lookups like T[K]." },
  { topic: "typescript", q: "What does the satisfies operator do?", c: ["Casts and widens to the target type", "Runtime-validates the value", "Checks against a type while keeping the narrower inferred type", "Marks a value as readonly"], a: 2, x: "x satisfies T type-checks x against T but keeps x's own inferred (often narrower) type - unlike a plain annotation." },
  { topic: "typescript", q: "Where do TypeScript types exist at runtime?", c: ["Nowhere - they are fully erased", "In a __types metadata object", "Only for classes", "In source maps"], a: 0, x: "Compilation strips every type; if you need a runtime check you must write one (or generate one) yourself." },
  { topic: "typescript", q: "The never type is best used for...", c: ["Optional properties", "Uninitialized variables", "Async rejections", "Exhaustiveness checks that fail to compile when a case is missed"], a: 3, x: "Assigning the leftover value to never in a default branch makes the compiler flag any union member you forgot to handle." },
  { topic: "typescript", q: "What does a?.b evaluate to when a is null?", c: ["It throws", "null", "undefined", "false"], a: 2, x: "Optional chaining short-circuits to undefined (never null) as soon as the receiver is null or undefined." },
  // ── javascript ──
  { topic: "javascript", q: "== differs from === because == ...", c: ["compares references", "coerces types before comparing", "is faster", "only works on primitives"], a: 1, x: "Loose equality applies coercion rules ('' == 0 is true); === compares type and value - the safe default." },
  { topic: "javascript", q: "When do promise .then callbacks run?", c: ["Immediately, synchronously", "On the next macrotask", "As microtasks after the current task, before rendering", "On a worker thread"], a: 2, x: "Settled promise reactions queue as microtasks - they run after the current stack empties but before timers and paint." },
  { topic: "javascript", q: "const obj = {} prevents what?", c: ["Rebinding obj to another value", "Mutating obj's properties", "Deleting obj", "Freezing the prototype"], a: 0, x: "const locks the BINDING, not the value - obj.x = 1 is fine; obj = {} throws. Object.freeze governs mutation." },
  { topic: "javascript", q: "A closure is a function that...", c: ["runs exactly once", "captures the variables of the scope it was created in", "has no this binding", "is defined inside a class"], a: 1, x: "Functions keep a live reference to their defining scope - the basis of module patterns, callbacks and private state." },
  { topic: "javascript", q: "What does await actually block?", c: ["The whole event loop", "All other promises", "Only the async function it appears in", "The rendering thread"], a: 2, x: "await suspends just that async function until the promise settles; the event loop keeps servicing everything else." },
  { topic: "javascript", q: "Array.prototype.map returns...", c: ["The same array, mutated", "A new array of callback results, same length", "Only the truthy results", "An iterator"], a: 1, x: "map is 1:1 and non-mutating; filter changes length, forEach returns nothing - picking the right one states intent." },
  // ── git ──
  { topic: "git", q: "git rebase -i onto an earlier commit lets you...", c: ["edit, squash, drop and reorder commits", "merge without a commit", "inspect remote refs", "sign old tags"], a: 0, x: "Interactive rebase rewrites the picked range - reword, squash, drop, reorder - producing NEW commit hashes." },
  { topic: "git", q: "What does git stash do?", c: ["Deletes untracked files", "Creates a temporary branch", "Shelves uncommitted changes to restore later", "Squashes the last commit"], a: 2, x: "stash parks your dirty working tree (and index) so you can switch context, then `git stash pop` brings it back." },
  { topic: "git", q: "HEAD normally points to...", c: ["The newest commit in the repo", "The remote default branch", "Your staging area", "The branch ref you have checked out"], a: 3, x: "HEAD → refs/heads/<branch> → commit. Checking out a raw commit detaches HEAD - commits there need a branch to survive." },
  { topic: "git", q: "Rebase vs merge: rebase...", c: ["replays your commits onto a new base for linear history", "keeps both histories with a join commit", "never rewrites hashes", "only works on remotes"], a: 0, x: "Rebase rewrites your commits on top of the target (clean line, new hashes); merge preserves both lines with a merge commit." },
  { topic: "git", q: "git cherry-pick <sha> does what?", c: ["Moves the commit to another repo", "Applies that commit's changes as a new commit here", "Reverts the commit", "Tags the commit"], a: 1, x: "cherry-pick copies one commit's diff onto the current branch as a fresh commit - useful for surgical backports." },
  { topic: "git", q: "Adding a tracked file to .gitignore does what?", c: ["Untracks it immediately", "Deletes it from history", "Nothing - ignore rules only affect untracked files", "Blocks future commits touching it"], a: 2, x: "Ignore patterns never apply to files already tracked - you need `git rm --cached <file>` to stop tracking it." },
  // ── security ──
  { topic: "security", q: "Prompt injection is when...", c: ["a model leaks its system prompt", "untrusted content smuggles instructions into a model's prompt", "a prompt exceeds the context window", "two prompts collide in a cache"], a: 1, x: "Data the model reads (files, pages, tool output) can carry adversarial instructions - treat retrieved content as data, never as commands." },
  { topic: "security", q: "XSS becomes possible when...", c: ["untrusted input is rendered as HTML or script", "cookies lack expiry", "TLS is misconfigured", "passwords are unhashed"], a: 0, x: "Cross-site scripting is an output-encoding failure: escape untrusted text for its context (HTML, attribute, JS) or it executes." },
  { topic: "security", q: "The primary defense against SQL injection?", c: ["Escaping quotes by hand", "A web application firewall", "Hiding error messages", "Parameterized queries"], a: 3, x: "Prepared statements keep code and data on separate channels - the value can never be parsed as SQL, whatever it contains." },
  { topic: "security", q: "Least privilege means...", c: ["admins approve every action", "each component gets only the access its job needs", "all secrets live in one vault", "users cannot install software"], a: 1, x: "Scoping tokens, roles and file access to the minimum turns a compromise of one part into a small blast radius." },
  { topic: "security", q: "A fail-closed design responds to an internal error by...", c: ["denying or blocking the action", "logging and continuing", "retrying until success", "falling back to defaults"], a: 0, x: "When the checker itself fails you cannot know the input is safe - so the gate blocks. Fail-open turns outages into bypasses." },
  { topic: "security", q: "Trojan Source attacks hide malicious logic using...", c: ["homoglyph domain names", "polyglot file headers", "Unicode bidi controls that reorder how code displays", "zip bombs"], a: 2, x: "Bidi override characters make source read differently than it parses - reviewers see one program, compilers another." },
  { topic: "security", q: "CSRF tricks a victim's browser into...", c: ["running injected script", "sending an authenticated state-changing request to another site", "downgrading TLS", "leaking localStorage"], a: 1, x: "The browser auto-attaches cookies, so a hostile page can forge requests - SameSite cookies and CSRF tokens break it." },
  { topic: "security", q: "A supply-chain attack compromises you via...", c: ["a dependency, build step or update channel you trust", "brute-forced credentials", "an exposed debug port", "social engineering only"], a: 0, x: "Poisoning one popular package or build pipeline reaches every downstream user - pin, verify and audit what you pull in." },
  // ── ml ──
  { topic: "ml", q: "In PyTorch, tensor.detach() returns...", c: ["a CPU copy", "a tensor cut out of the autograd graph", "a tensor with gradients zeroed", "a NumPy view"], a: 1, x: "detach() shares the same storage but records no gradient history - the standard way to stop backprop through a value." },
  { topic: "ml", q: "loss.backward() does what?", c: ["Applies the optimizer step", "Resets the computation graph", "Computes gradients of the loss w.r.t. tracked tensors", "Normalizes the loss"], a: 2, x: "backward() runs reverse-mode autodiff, filling .grad on every tensor with requires_grad=True along the graph." },
  { topic: "ml", q: "Why call optimizer.zero_grad() each step?", c: ["PyTorch accumulates gradients across backward calls", "It frees GPU memory", "It reshuffles the batch", "It decays the learning rate"], a: 0, x: "Gradients ADD UP by design (useful for accumulation); forget to zero them and every step applies stale gradient sums." },
  { topic: "ml", q: "model.eval() switches...", c: ["off gradient tracking", "dropout and batchnorm to inference behavior", "the model to half precision", "to the validation dataset"], a: 1, x: "eval() flips layer modes only - dropout stops dropping, batchnorm uses running stats. no_grad() is a separate, second switch." },
  { topic: "ml", q: "Overfitting shows up as...", c: ["high loss on both splits", "slow convergence", "exploding gradients", "great training metrics but poor unseen-data metrics"], a: 3, x: "The model memorized the training set instead of generalizing - fight it with more data, regularization or early stopping." },
  { topic: "ml", q: "A learning rate set too high typically causes...", c: ["the loss to diverge or oscillate", "underfitting only", "vanishing gradients", "slower epochs"], a: 0, x: "Steps overshoot the minimum, so loss bounces or explodes; too LOW converges slowly - LR schedules balance the two." },
  { topic: "ml", q: "torch.no_grad() is used to...", c: ["freeze model weights permanently", "run ops without recording autograd history", "disable dropout", "pin tensors to the CPU"], a: 1, x: "Inside the context no graph is built - faster, lighter inference. Weights stay trainable once you leave the block." },
  { topic: "ml", q: "In transformers, self-attention lets each token...", c: ["see only the previous token", "share weights with its neighbors", "weigh every other position when building its representation", "skip the feed-forward layer"], a: 2, x: "Attention scores decide how much each position contributes to each other position - the mechanism behind long-range context." },
  // ── web ──
  { topic: "web", q: "HTTP 304 Not Modified tells the client...", c: ["the resource moved", "its cached copy is still valid - use it", "the server is overloaded", "authentication expired"], a: 1, x: "A conditional request (If-None-Match / If-Modified-Since) hit: no body is resent, the cache serves the bytes." },
  { topic: "web", q: "Who actually enforces CORS?", c: ["The server firewall", "The CDN", "The browser, based on response headers", "The DNS resolver"], a: 2, x: "Servers only DECLARE policy via Access-Control-* headers; the browser blocks the reading side. curl ignores CORS entirely." },
  { topic: "web", q: "localStorage vs sessionStorage:", c: ["localStorage persists across browser restarts", "sessionStorage is shared across tabs", "localStorage is per-request", "sessionStorage survives reboots"], a: 0, x: "Both are per-origin; sessionStorage dies with the tab, localStorage stays until cleared - neither belongs to sensitive secrets." },
  { topic: "web", q: "<script defer> means the script...", c: ["runs before any HTML parses", "downloads in parallel and runs after parsing, in order", "runs only on user interaction", "is loaded as a module"], a: 1, x: "defer keeps parsing unblocked and preserves execution order; async also downloads in parallel but fires whenever it lands." },
  { topic: "web", q: "HTTPS by itself guarantees...", c: ["the site's code is safe", "confidentiality and integrity in transit", "no cookies are set", "the server is patched"], a: 1, x: "TLS protects the pipe (encryption + tamper detection + server identity) - it says nothing about what the server does with your data." },
  { topic: "web", q: "An idempotent HTTP method is one where...", c: ["repeating the request leaves the same end state", "the response is cacheable", "no body is allowed", "authentication is skipped"], a: 0, x: "PUT and DELETE are specified as idempotent (safe to retry); POST is not - which is why retry logic treats it carefully." },
  // ── cs ──
  { topic: "cs", q: "Binary search on n sorted items costs...", c: ["O(n)", "O(n log n)", "O(log n)", "O(1)"], a: 2, x: "Each probe halves the remaining range, so 1,000,000 items need about 20 comparisons." },
  { topic: "cs", q: "Average-case lookup in a hash map is...", c: ["O(log n)", "O(1)", "O(n)", "O(n log n)"], a: 1, x: "Hashing jumps straight to a bucket; collisions degrade it, which is why the worst case is O(n) with a bad hash." },
  { topic: "cs", q: "A race condition means...", c: ["two processes deadlock", "the outcome depends on the timing of concurrent operations", "a loop never terminates", "memory leaks under load"], a: 1, x: "Unsynchronized check-then-act windows let interleavings produce different results - locks or atomics close the window." },
  { topic: "cs", q: "Stack vs queue:", c: ["LIFO vs FIFO", "FIFO vs LIFO", "Both are FIFO", "Both are LIFO"], a: 0, x: "A stack pops what you pushed last (call stacks, undo); a queue serves in arrival order (task queues, BFS)." },
  { topic: "cs", q: "A mutex exists to...", c: ["speed up context switches", "let one thread at a time enter a critical section", "schedule threads fairly", "detect deadlocks"], a: 1, x: "Mutual exclusion serializes access to shared state; holding it briefly and consistently is what prevents races." },
  { topic: "cs", q: "UTF-8 encodes a code point using...", c: ["always 2 bytes", "always 4 bytes", "1 to 4 bytes, ASCII-compatible", "a byte-order mark per string"], a: 2, x: "ASCII stays 1 byte (unchanged), everything else takes 2-4 - why UTF-8 won as the interchange default." },
  // ── P-TRIV.3 (ADR-0176) expansion to 100 ──
  { topic: "python", q: "In Python, what does `is` test?", c: ["Value equality", "Object identity - same object in memory", "Type compatibility", "Truthiness"], a: 1, x: "`is` compares identity, `==` compares values - small-int caching makes `is` seem to work on numbers until it doesn't." },
  { topic: "python", q: "Since Python 3.7, what order do dicts iterate in?", c: ["Unspecified order", "Sorted key order", "Insertion order, guaranteed by the language", "Hash order"], a: 2, x: "Insertion order was an implementation detail in 3.6 and became a language guarantee in 3.7 - no OrderedDict needed for order alone." },
  { topic: "python", q: "In def f(*args, **kwargs), what does **kwargs collect?", c: ["Extra keyword arguments into a dict", "All arguments as a list", "Global variables", "Type annotations"], a: 0, x: "*args packs extra positionals into a tuple; **kwargs packs extra keyword arguments into a dict." },
  { topic: "python", q: "In try/except/else, when does the else block run?", c: ["Always", "When an exception was caught", "Only inside loops", "When the try body raised no exception"], a: 3, x: "else runs only if try raised nothing - it keeps happy-path code out of the except net so its errors aren't swallowed." },
  { topic: "python", q: "What does -7 // 2 evaluate to in Python?", c: ["-3", "-4", "-3.5", "4"], a: 1, x: "// floors toward negative infinity, not toward zero - so -7 // 2 is -4 while int(-7 / 2) is -3." },
  { topic: "python", q: "A Python decorator is fundamentally...", c: ["a callable that takes and returns a function", "a comment convention", "a compiler directive", "a class-only feature"], a: 0, x: "@deco is sugar for f = deco(f) - the decorator receives the function and whatever it returns gets bound to the name." },
  { topic: "typescript", q: "Declaring the same name twice merges members for which construct?", c: ["A type alias", "An interface", "A const", "A generic parameter"], a: 1, x: "Two interface declarations with one name merge their members; redeclaring a type alias is a compile error." },
  { topic: "typescript", q: "What does Partial<T> produce?", c: ["A deep-optional version of T", "T with methods removed", "T with every property optional (shallow)", "A runtime validator"], a: 2, x: "Partial is a mapped type adding ? to each top-level property - the standard shape for update/patch objects; nesting is untouched." },
  { topic: "typescript", q: "What does `as const` do to a literal?", c: ["Freezes it at runtime", "Converts it to an enum", "Widens it to string", "Narrows it to readonly literal types"], a: 3, x: "as const infers the narrowest readonly types: [\"a\"] becomes readonly [\"a\"] instead of string[] - purely compile-time." },
  { topic: "typescript", q: "A return type of `x is Cat` makes the function...", c: ["a type guard that narrows x for the compiler", "a runtime cast", "an assertion that throws", "a decorator"], a: 0, x: "A user-defined type guard returns a boolean the compiler trusts: in the true branch, x is narrowed to Cat." },
  { topic: "typescript", q: "With strictNullChecks disabled, null and undefined are...", c: ["compile errors everywhere", "only valid in unions", "assignable to almost every type", "runtime-checked"], a: 2, x: "Without strictNullChecks they silently belong to every type, so the compiler cannot catch missing-value bugs - turn it on." },
  { topic: "javascript", q: "What does typeof null return?", c: ["\"null\"", "\"undefined\"", "\"object\"", "\"boolean\""], a: 2, x: "A day-one type-tag bug kept for web compatibility - use x === null to test for null, never typeof." },
  { topic: "javascript", q: "Reading a `let` variable before its declaration does what?", c: ["Returns undefined", "Throws a ReferenceError", "Returns null", "Hoists the value"], a: 1, x: "let/const are hoisted but uninitialized - the temporal dead zone throws instead of yielding undefined like var does." },
  { topic: "javascript", q: "Where does an arrow function get its `this`?", c: ["From the caller", "From the global object", "It has none at all", "From the enclosing lexical scope"], a: 3, x: "Arrows do not bind their own this - they capture the enclosing scope's, so call-site tricks like .bind have no effect." },
  { topic: "javascript", q: "Which JavaScript value is not equal to itself?", c: ["null", "undefined", "-0", "NaN"], a: 3, x: "IEEE 754 defines NaN as unequal to everything, including itself - use Number.isNaN(x) to test for it." },
  { topic: "javascript", q: "Copying an object with {...obj} gives you...", c: ["a shallow copy - nested objects still shared", "a deep copy", "a frozen copy", "a reference, not a copy"], a: 0, x: "Spread copies one level of own enumerable properties; nested objects remain shared references - structuredClone goes deep." },
  { topic: "javascript", q: "JSON.stringify omits which object property values?", c: ["null values", "undefined, functions and symbols", "empty strings", "zero and false"], a: 1, x: "They are not valid JSON, so stringify drops them from objects (and writes null for them in arrays)." },
  { topic: "git", q: "How does git fetch differ from git pull?", c: ["fetch downloads refs without changing your branch", "fetch also merges", "pull is read-only", "they are identical"], a: 0, x: "fetch only updates remote-tracking refs; pull is fetch plus a merge (or rebase) into your current branch." },
  { topic: "git", q: "The safe way to undo a commit already pushed and shared?", c: ["git reset --hard", "git commit --amend", "git revert - a new commit that undoes it", "delete the branch"], a: 2, x: "revert records an inverse commit instead of rewriting history, so collaborators' clones stay consistent." },
  { topic: "git", q: "How does git bisect locate a regression?", c: ["By scanning commit messages", "By diffing the newest commit", "By blaming each line", "Binary search over history using your good/bad marks"], a: 3, x: "You mark commits good or bad and git halves the range each step - 1024 commits take about 10 tests." },
  { topic: "git", q: "git commit --amend does what?", c: ["Replaces the tip commit with a new one (new hash)", "Edits the commit in place, same hash", "Squashes the last two commits", "Reverts the last commit"], a: 0, x: "amend rewrites the tip into a NEW commit - fine locally, but avoid it on commits already pushed and shared." },
  { topic: "git", q: "You hard-reset away commits by mistake. Where do you look?", c: ["git fsck only", "git reflog - the local log of HEAD moves", "the remote server", "they are gone"], a: 1, x: "The reflog journals every HEAD move for weeks, so \"lost\" commits are still reachable and recoverable from it." },
  { topic: "security", q: "Passwords should be stored using...", c: ["reversible encryption", "plain SHA-256", "a slow adaptive hash like bcrypt or Argon2", "base64 encoding"], a: 2, x: "Fast hashes invite offline brute force; bcrypt/scrypt/Argon2 are deliberately slow and tunable as hardware improves." },
  { topic: "security", q: "Why salt password hashes with a unique per-user value?", c: ["It encrypts the password", "It defeats precomputed rainbow tables", "It speeds up login", "It hides the username"], a: 1, x: "A unique salt makes precomputed tables useless and stops identical passwords from producing identical hashes." },
  { topic: "security", q: "What does the HttpOnly cookie flag do?", c: ["Blocks the cookie over HTTPS", "Encrypts the cookie", "Limits the cookie to GET requests", "Hides the cookie from JavaScript"], a: 3, x: "HttpOnly keeps document.cookie from reading the value, so XSS cannot simply exfiltrate the session token." },
  { topic: "security", q: "A path traversal attack uses ../ sequences to...", c: ["escape the intended directory and read other files", "overflow the URL buffer", "poison the DNS cache", "bypass TLS"], a: 0, x: "User input reaching a file path unchecked lets ../../etc/passwd walk out of the web root - canonicalize, then validate." },
  { topic: "security", q: "An SSRF vulnerability lets an attacker...", c: ["run SQL on the server", "steal browser cookies", "make the server request URLs of their choosing", "crack password hashes"], a: 2, x: "Server-side request forgery abuses URL-fetching features to reach internal services and cloud metadata endpoints." },
  { topic: "security", q: "You accidentally committed an API key. The correct response?", c: ["Delete the file in a new commit", "Force-push to remove the commit", "Wait and monitor usage", "Rotate the key immediately"], a: 3, x: "Clones, forks, caches and mirrors keep old commits - the only safe response to a leaked credential is rotation." },
  { topic: "ml", q: "Softmax converts a vector of logits into...", c: ["a probability distribution summing to 1", "binary labels", "normalized gradients", "one-hot vectors"], a: 0, x: "Softmax exponentiates and normalizes the logits so they sum to 1 - the standard final layer for classification." },
  { topic: "ml", q: "In an LLM, an embedding layer maps each token to...", c: ["a unique integer", "a dense vector where distance tracks similarity", "a probability", "an attention head"], a: 1, x: "Embeddings place tokens in a continuous space where nearness means relatedness - the input to every transformer layer stack." },
  { topic: "ml", q: "Raising sampling temperature does what to LLM output?", c: ["Shortens it", "Makes it deterministic", "Flattens the distribution - more varied, riskier picks", "Extends the context window"], a: 2, x: "Logits are divided by T before softmax: higher T flattens the distribution; T near 0 approaches greedy decoding." },
  { topic: "ml", q: "What is data leakage in an ML pipeline?", c: ["GPU memory overflow", "Test-set or future information reaching training", "Publishing the dataset", "Gradient values leaking to logs"], a: 1, x: "When evaluation signal sneaks into training, offline metrics look great and production disappoints - audit the split." },
  { topic: "ml", q: "The standard loss for multi-class classification is...", c: ["mean squared error", "hinge loss", "L1 loss", "cross-entropy"], a: 3, x: "Cross-entropy pairs naturally with softmax outputs and punishes confident wrong predictions heavily." },
  { topic: "ml", q: "RAG improves LLM answers by...", c: ["retrieving relevant documents into the prompt", "retraining nightly", "raising the temperature", "quantizing the weights"], a: 0, x: "Retrieval-augmented generation grounds answers in fetched context at query time - fresher facts without retraining." },
  { topic: "web", q: "HTTP 401 vs 403:", c: ["401 = banned IP, 403 = bad password", "Both mean login failed", "401 = not authenticated, 403 = authenticated but denied", "403 retries automatically"], a: 2, x: "401 means \"try credentials\"; 403 means \"we know who you are and the answer is still no\"." },
  { topic: "web", q: "What does DNS fundamentally do?", c: ["Encrypts web traffic", "Resolves domain names to IP addresses", "Balances server load", "Compresses HTTP headers"], a: 1, x: "Resolvers walk root, TLD and authoritative servers to map a name to addresses, then cache the answer per its TTL." },
  { topic: "web", q: "What does a WebSocket give you that plain HTTP does not?", c: ["Lower-latency DNS", "Automatic caching", "Built-in encryption", "A persistent two-way channel - either side can push"], a: 3, x: "After an HTTP upgrade handshake, both ends can send frames anytime - no request/response pairing, no polling." },
  { topic: "web", q: "A CDN mainly speeds up a site by...", c: ["minifying your JavaScript", "upgrading you to HTTP/3", "serving cached content from edges near the user", "compressing images"], a: 2, x: "Edge caching cuts round-trip latency and offloads the origin - the biggest win for static assets and media." },
  { topic: "web", q: "HTTP/2 multiplexing means...", c: ["many concurrent streams share one connection", "each request opens a socket", "responses arrive in request order only", "headers are unencrypted"], a: 0, x: "One TCP connection carries many interleaved streams, removing HTTP/1.1's one-request-at-a-time queue per connection." },
  { topic: "cs", q: "Quicksort's worst-case time complexity is...", c: ["O(n log n)", "O(n^2)", "O(log n)", "O(n)"], a: 1, x: "A consistently bad pivot (e.g. first element on sorted input) degrades it to quadratic; random pivots make that rare." },
  { topic: "cs", q: "Which condition is required for deadlock?", c: ["A single-core CPU", "Shared read-only data", "A circular wait among lock holders", "Priority scheduling"], a: 2, x: "Coffman conditions: mutual exclusion, hold-and-wait, no preemption, circular wait - break any one and deadlock is impossible." },
  { topic: "cs", q: "Why does 0.1 + 0.2 differ from 0.3 in IEEE 754 floats?", c: ["A rounding-mode bug", "Integer overflow", "Parser precision limits", "0.1 and 0.2 have no exact binary representation"], a: 3, x: "Binary floats are sums of powers of 2; 0.1 and 0.2 repeat infinitely in base 2, so the sum carries rounding error." },
  { topic: "cs", q: "Two's complement is the standard way to...", c: ["represent signed integers in binary", "encode floating-point numbers", "compress bit strings", "hash keys"], a: 0, x: "It yields a single zero and lets the same adder circuit handle signed and unsigned values - why it won." },
  { topic: "cs", q: "Where do arrays clearly beat linked lists?", c: ["Insertion at a known node", "Growing without copying", "Splicing two lists", "O(1) random access by index"], a: 3, x: "Contiguous memory makes arr[i] one address computation; a linked list must walk i nodes to reach the same element." },
];
