// Copyright (c) 2026 TechLead 187 LLC
// SPDX-License-Identifier: BUSL-1.1

// desktop/packaged_boot.test.ts — ADR-0177: the engine must BOOT under the packaging filter.
//
// Reproduces the v1.10.2 brick class in CI. electron-builder's extraResources filter strips file
// classes out of node_modules; v1.10.2 shipped with "!node_modules/**/*.md" while the engine's new
// import graph loaded @oh-my-pi/pi-coding-agent, which imports its prompt .md files at module load -
// so the packaged engine died before binding its port and the app opened to the "could not start
// its local engine" dialog. My packaged-layout simulation missed it because it junctioned a REAL
// node_modules (with the .md files still present).
//
// This test closes the gap for good: it reads the LIVE filter from desktop/package.json, EMULATES
// every node_modules exclusion with a Bun resolver plugin (an excluded file fails to resolve exactly
// as if packaging had stripped it), boots the REAL dev.ts, and requires /api/health to answer.
// Re-add a filter the engine needs - or add an import the current filter strips - and this fails in
// CI instead of shipping a bricked installer.

import { expect, test } from "bun:test";
import { spawn } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

interface ResourceEntry { to?: string; filter?: string[] }

function nodeModulesExclusions(): string[] {
  const pkg = JSON.parse(readFileSync(join(import.meta.dir, "package.json"), "utf8")) as { build?: { extraResources?: ResourceEntry[] } };
  const repo = (pkg.build?.extraResources ?? []).find((r) => r?.to === "repo");
  return (repo?.filter ?? []).filter((f) => f.startsWith("!node_modules"));
}

test("the engine boots with the packaging filter's node_modules exclusions emulated", async () => {
  const exclusions = nodeModulesExclusions();
  expect(exclusions.length).toBeGreaterThan(0); // the filter moved? update this test with it

  const dir = mkdtempSync(join(tmpdir(), "lucid-pkgboot-"));
  const preload = join(dir, "guard.ts");
  writeFileSync(preload, `
// generated by packaged_boot.test.ts - emulates ${JSON.stringify(exclusions.length)} packaging exclusions
const EXCLUSIONS: string[] = ${JSON.stringify(exclusions)};
const suffixes = EXCLUSIONS.map((e) => /^!node_modules\\/\\*\\*\\/\\*(\\.[a-z.]+)$/.exec(e)?.[1]).filter((s): s is string => !!s);
const subtrees = EXCLUSIONS.map((e) => /^!node_modules\\/([^*]+?)\\/?\\*\\*$/.exec(e)?.[1]).filter((s): s is string => !!s);
Bun.plugin({
  name: "packaging-filter-emulation",
  setup(b) {
    b.onResolve({ filter: /./ }, (args) => {
      const spec = args.path.replace(/\\\\/g, "/");
      const importer = (args.importer ?? "").replace(/\\\\/g, "/");
      const touchesNM = importer.includes("node_modules") || spec.includes("node_modules");
      if (touchesNM && suffixes.some((s) => spec.endsWith(s))) {
        throw new Error("excluded by packaging filter (emulated): " + spec + " from " + importer);
      }
      if (subtrees.some((t) => spec === t || spec.startsWith(t + "/") || spec.includes("node_modules/" + t))) {
        throw new Error("excluded by packaging filter (emulated): " + spec);
      }
      return undefined; // not excluded - fall through to the normal resolver
    });
  },
});
`);

  const port = 5400 + Math.floor(Math.random() * 400);
  const devTs = join(import.meta.dir, "dev.ts");
  const child = spawn(process.execPath, ["--preload", preload, devTs], {
    cwd: join(import.meta.dir, ".."),
    env: { ...process.env, PORT: String(port) },
    stdio: ["ignore", "pipe", "pipe"],
  });
  let out = "";
  child.stdout?.on("data", (d) => { out += String(d); });
  child.stderr?.on("data", (d) => { out += String(d); });

  try {
    const deadline = Date.now() + 25_000;
    let up = false;
    while (Date.now() < deadline && !up && child.exitCode === null) {
      try { up = (await fetch(`http://localhost:${port}/api/health`)).ok; }
      catch { await new Promise((r) => setTimeout(r, 300)); }
    }
    if (!up) throw new Error(`engine did not boot under the emulated packaging filter (exit=${child.exitCode}). Engine output:\n${out.slice(-2000)}`);
    expect(up).toBe(true);
  } finally {
    try { child.kill(); } catch { /* already gone */ }
  }
}, 45_000);
